### ISSUE TITLE
This repository should be made obsolete

### ISSUE THREAD

**Issue by vandadnp** [onmyway133/Smile#27]
Since there is no active development on this repository since Nov 2018 (that's when 2.0.0 came out as a Pod) and no newer versions are released, I believe it is your duty to make it clear in the README.md that this repository is not actively maintained and people should steer clear of it. We have this repository as a dependency and now we have to do a lot of work to get rid of it. Thank you.

**Comment by NSMyself** [comment]
@vandadnp Perhaps people should come to this conclusion themselves instead of blindly picking a dependency that is no longer being actively maintained.

FYI, it is also our duty as responsible users to reduce the toxicity of OSS (and IT in general). The tone you picked to create this issue is just dreadful.

**Comment by jordibruin** [comment]
You can also add any missing features as PRs if you feel the library is missing something.

**Comment by vandadnp** [comment]
> @vandadnp Perhaps people should come to this conclusion themselves instead of blindly picking a dependency that is no longer being actively maintained.
> 
> FYI, it is also our duty as responsible users to reduce the toxicity of OSS (and IT in general). The tone you picked to create this issue is just dreadful.

Though your tone is a clear attack, I'll maintain professionalism and remind you and any maintainers of this repository that is your duty to tell everyone who is thinking of adopting this outdated repository that they should steer clear of it.

No active maintenance + obnoxious replies from you and people like you + no clear indication as to obsoleteness of this repository is a recipe for disaster.

This repository was adopted in our codebase about 4 years ago before I even started working on it and now we need to spend countless hours of our precious time to fix a mistake that could be avoided had the maintainers of this repository clearly communicated with everyone that it is not going to be maintained actively.

Please keep a professional tone in your communication so we can have a constructive discussion. Just because you don't like my suggestion doesn't mean you should get offended.

**Comment by ioscafe** [comment]
> @vandadnp Perhaps people should come to this conclusion themselves instead of blindly picking a dependency that is no longer being actively maintained.

How is this response considered OK?! OP is asking if this repo could be marked as obsolete, which to me is a valid thing to ask (not judging anybody's tone) and all you are saying is "blindly picking" and later calling their request toxic and completely dismissing the original issue?

The issue as I can also see is that @ onmyway133 (or any other person for that matter) has not been able to dedicate any time to this repository in the last ... 1-2 years so it's completely reasonable to ask for this repo to be marked as not maintained imho.

I suggest that everyone keeps a friendly tone and focus on the state of this repository which to me seems like the original topic.

**Comment by vandadnp** [comment]
> > @vandadnp Perhaps people should come to this conclusion themselves instead of blindly picking a dependency that is no longer being actively maintained.
> 
> How is this response considered OK?! OP is asking if this repo could be marked as obsolete, which to me is a valid thing to ask (not judging anybody's tone) and all you are saying is "blindly picking" and later calling their request toxic and completely dismissing the original issue?
> 
> The issue as I can also see is that @onmyway133 (or any other person for that matter) has not been able to dedicate any time to this repository in the last ... 1-2 years so it's completely reasonable to ask for this repo to be marked as not maintained imho.
> 
> I suggest that everyone keeps a friendly tone and focus on the state of this repository which to me seems like the original topic.

I hope I haven't offended anybody by my suggestion. it is concerning to have a repository available Cocoapods while it is in essence unmaintained and lack of features. I personally can live with lack of features, but lack of maintainers is a red flag and should be clearly marked.

In other GitHub organizations people put up unmaintained repositories as needing "adopters" or maintainers and if nobody can step up to become the main adopter, it is marked as obsolete.

**Comment by vandadnp** [comment]
> > > @vandadnp In other GitHub organizations people put up unmaintained repositories as needing "adopters" or maintainers and if nobody can step up to become the main adopter, it is marked as obsolete.

can you please provide an example

**Comment by ioscafe** [comment]
@vandadnp can you provide an example of such a repo please? just so I see what you mean by adoption

**Comment by NSMyself** [comment]
@ioscafe Alright, fair point. 
@vandadnp I apologise for the rant above. The tone of this post triggered me though and I shouldn't have reacted the way I did. I will delete the comment above.

For the record I'm in no way affiliated with this repository or the author in any case.

> This repository was adopted in our codebase about 4 years ago before I even started working on it and now we need to spend countless hours of our precious time to fix a mistake that could be avoided had the maintainers of this repository clearly communicated with everyone that it is not going to be maintained actively.

Couple of things here:

1. @onmyway133 is in no way liable for problems on your codebase
2. Last release was last year
3. I understand how frustrating this kind of issues can but spending countless hours trying to decouple your code from this library seem really weird, considering the nature of this library
4. What issues does this library have specifically are affecting you in order to consider dropping the library? That would have been very useful information

**Comment by ioscafe** [comment]
> @NSMyself no problems, thanks for your message.
> 
> I just want to clarify that I stated incorrectly that others call this process "adoption". It's called "stewardship" apparently and here is an example which I am aware of: [RxSwiftCommunity/RxCoreData#28](https://github.com/RxSwiftCommunity/RxCoreData/issues/28)
> 
> RxCoreData repository has not had so much luck getting PRs merged in and issues fixed so they need a main person carrying the burden and fixing issues and merging pull requests so it's stewardship that I'm talking about here.
> 
> So if we look at the available issues in this repository, it becomes immediately obvious what issues I am talking about. If this repository is to be "maintained", it needs a main person leading that maintenance and taking care of pull request merges, replies to issues, fixing issues, etc.

thank you. I read the discussion and it seems like the Rx thing is an organization and that's why they could invite a new person to the organization and set as the "steward". am I right?

The Smile repository itself is not an organization though so I don't think we can invite others to just become stewards BUT I think it's a valid point to find a person who can take care of the stewardship of this project if @onmyway133 doesn't have the time to do so. I don't know how it works in GitHub but I think this should be the process

1. put up an issue asking for people to become stewards of this project
2. once we find someone we need a way to get that person to become the maintainer of this project. perhaps @onmyway133 will need to solve that since this repository is under his account
3. profit?

**Comment by ioscafe** [comment]
@onmyway133 Hi

Due to inactivity it's perhaps best to just close this issue. What are your thoughts? I've contacted OP on Slack and he mentioned that an admin of this repo has blocked his access so he can no longer comment here or close it apparently. If the OP cannot contribute to this post, then perhaps you could clarify what your plan is for "stewardship" or what the next step is! Otherwise maybe there is no value in having this issue open and could safely be closed
